### ISSUE TITLE
Connection refused 

### ISSUE THREAD

**Issue by shelbyspees** [ConnectingRestaurants/projectb#3]
Is the server running on host "0.0.0.0" and accepting TCP/IP connections on port 5432?

![image](https://cloud.githubusercontent.com/assets/5217772/11196059/46eb12b0-8c6a-11e5-8e21-8ba1f934dfea.png)

Do you get the same error if you run 

    rails server -b $IP -p $PORT

from Cloud9?

**Comment by andrewjgremmo** [comment]
Try running the steps from this post:

http://stackoverflow.com/a/27707293

**Comment by shelbyspees** [comment]
That fixed it, thanks. The environment variables for username and password are smart.
